version: 2
jobs:
  build:
    working_directory: ~/dmc
    docker:
      - image: circleci/node:8.11.0
      - image: mongo:4.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "mkdir salam"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  build_and_deploy:
    jobs:
      - build
      - deploy_on:
          - deploy
          context: Staging
          requires:
            - build
          filters:
            branches:
              only: master