version: 2
jobs:
  build:
    working_directory: ~/dmc
    docker:
      - image: circleci/node:8.11.0
      - image: mongo:4.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test